
server:
  port: 9000
spring:
  application:
    name: bank-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6000/bank_service_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true