
###
GET /security/csrf-token
Host: localhost:9000


### IdentityRequests


###
POST /identities/create
Host: localhost:9000
Content-Type: application/json

{
    "authority": "ADMIN",
    "name": "Igor",
    "surname": "Polushev",
    "patronymic": "Petrovich",
    "password": "admin",
    "email": "admin@gmail.com",
    "phone": "+7(913)-905-7556",
    "passport": "4657 687943",
    "enabled": true
}

###
POST /identities/create
Host: localhost:9000
Content-Type: application/json

{
    "authority": "USER",
    "name": "Vadim",
    "surname": "Krivov",
    "patronymic": "Olegovich",
    "password": "user",
    "email": "user@gmail.com",
    "phone": "+7(952)-563-7942",
    "passport": "8696 761238",
    "enabled": true
}

###
POST /identities/create
Host: localhost:9000
Content-Type: application/json

{
    "authority": "EMPLOYEE",
    "name": "Svetlana",
    "surname": "Marlova",
    "patronymic": "Pavlovna",
    "password": "employee",
    "email": "employee@gmail.com",
    "phone": "+7(961)-294-5184",
    "passport": "8463 765238",
    "enabled": true
}

###
PUT /identities/update?identityId=acf2d526-b745-465c-b82f-cb07837f361c
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "phone": "+7(952)-295-5690"
}

###
GET /identities
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
GET /identities/by-email?email=user@gmail.com
Host: localhost:9000
Authorization: Basic user@gmail.com user

###
GET /identities/by-id?identityId=acf2d526-b745-465c-b82f-cb07837f361c
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
DELETE /identities/delete?identityId=acf2d526-b745-465c-b82f-cb07837f361c
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
PATCH /identities/change-password?identityId=41d8248f-826c-4f78-a818-94bd6c909aaa&password=adminadmin
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
PATCH /identities/enable-disable?identityId=36c26d47-ff67-47c9-a7ba-1a1d0de6f52b&enabled=true
Host: localhost:9000
Authorization: Basic admin@gmail.com admin


### Card Requests


###
POST /cards/create
Host: localhost:9000
Authorization: Basic employee@gmail.com employee
Content-Type: application/json

{
    "identityId": "cbe85795-7782-41d3-9e4a-8b290ba5aa98",
    "cardType": "DEBIT",
    "paymentSystem": "MIR",
    "years": 3,
    "pin": 2356
}

###
POST /cards/create
Host: localhost:9000
Authorization: Basic employee@gmail.com employee
Content-Type: application/json

{
    "identityId": "7a5be6cf-a722-4af9-a937-f3711b2ec298",
    "cardType": "DEBIT",
    "paymentSystem": "UNION_PAY",
    "years": 2,
    "pin": 1245
}

###
GET /cards/by-parameters?identityId=cbe85795-7782-41d3-9e4a-8b290ba5aa98
Host: localhost:9000
Authorization: Basic user@gmail.com user
Content-Type: application/json

{
    "number": "7241 2543 3505 6864",
    "validTill": "2028-06-16",
    "code": 847
}

###
PUT /cards/deposit?amount=2300.0
Host: localhost:9000
Content-Type: application/json

{
    "number": "7241 2543 3505 6864",
    "validTill": "2028-06-16",
    "code": 847,
    "pin": 2356
}

###
PUT /cards/withdraw?amount=300.0
Host: localhost:9000
Content-Type: application/json

{
    "number": "7241 2543 3505 6864",
    "validTill": "2028-06-16",
    "code": 847,
    "pin": 2356
}

###
PUT /cards/transfer?fromCardId=f4f9d2cd-1d65-41d0-ab89-9f647b7006e7&toCardId=d6e8dcdc-0433-45a7-b787-e53d4f0f4506&amount=500.0
Host: localhost:9000
Authorization: Basic user@gmail.com user

###
PUT /cards/transfer?fromCardId=d6e8dcdc-0433-45a7-b787-e53d4f0f4506&toCardId=f4f9d2cd-1d65-41d0-ab89-9f647b7006e7&amount=300.0
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
PUT /cards/activate-deactivate?cardId=7826aa63-18cf-4b5b-87f6-ec9b88c8b42b&enabled=true
Host: localhost:9000
Authorization: Basic admin@gmail.com admin


### Operation Requests


###
GET /operations/by-card?cardId=f4f9d2cd-1d65-41d0-ab89-9f647b7006e7
Host: localhost:9000
Authorization: Basic user@gmail.com user

###
GET /operations/by-identity?identityId=cbe85795-7782-41d3-9e4a-8b290ba5aa98
Host: localhost:9000
Authorization: Basic user@gmail.com user


### Transfer Requests


###
GET /transfers/by-sender-card?senderCardId=f4f9d2cd-1d65-41d0-ab89-9f647b7006e7
Host: localhost:9000
Authorization: Basic user@gmail.com user

###
GET /transfers/by-identity?identityId=cbe85795-7782-41d3-9e4a-8b290ba5aa98
Host: localhost:9000
Authorization: Basic user@gmail.com user