
###
GET /security/csrf-token
Host: localhost:9000

###
POST /identities/create
Host: localhost:9000
Content-Type: application/json

{
    "authority": "ADMIN",
    "name": "Igor",
    "surname": "Polushev",
    "patronymic": "Petrovich",
    "password": "admin",
    "email": "admin@gmail.com",
    "phone": "+7(913)-905-7556",
    "passport": "4657 687943",
    "enabled": true
}

###
POST /identities/create
Host: localhost:9000
Content-Type: application/json

{
    "authority": "USER",
    "name": "Vadim",
    "surname": "Krivov",
    "patronymic": "Olegovich",
    "password": "user",
    "email": "user@gmail.com",
    "phone": "+7(952)-563-7942",
    "passport": "8696 761238",
    "enabled": true
}

###
POST /identities/create
Host: localhost:9000
Content-Type: application/json

{
    "authority": "EMPLOYEE",
    "name": "Svetlana",
    "surname": "Marlova",
    "patronymic": "Pavlovna",
    "password": "employee",
    "email": "employee@gmail.com",
    "phone": "+7(961)-294-5184",
    "passport": "8463 765238",
    "enabled": true
}

###
PUT /identities/update?identityId=acf2d526-b745-465c-b82f-cb07837f361c
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "phone": "+7(952)-295-5690"
}

###
GET /identities
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
GET /identities/by-email?email=user@gmail.com
Host: localhost:9000
Authorization: Basic user@gmail.com user

###
GET /identities/by-id?identityId=acf2d526-b745-465c-b82f-cb07837f361c
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
DELETE /identities/delete?identityId=acf2d526-b745-465c-b82f-cb07837f361c
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
PATCH /identities/change-password?identityId=41d8248f-826c-4f78-a818-94bd6c909aaa&password=adminadmin
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
PATCH /identities/enable-disable?identityId=36c26d47-ff67-47c9-a7ba-1a1d0de6f52b&enabled=true
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
POST /cards/create
Host: localhost:9000
Authorization: Basic employee@gmail.com employee
Content-Type: application/json

{
    "identityId": "36c26d47-ff67-47c9-a7ba-1a1d0de6f52b",
    "cardType": "DEBIT",
    "paymentSystem": "MIR",
    "years": 3,
    "pin": 2356
}

###
POST /cards/create
Host: localhost:9000
Authorization: Basic employee@gmail.com employee
Content-Type: application/json

{
    "identityId": "72333a49-f56d-4dab-8883-85e8fcd7616b",
    "cardType": "DEBIT",
    "paymentSystem": "UNION_PAY",
    "years": 2,
    "pin": 1245
}

###
GET /cards/by-parameters?identityId=36c26d47-ff67-47c9-a7ba-1a1d0de6f52b
Host: localhost:9000
Authorization: Basic user@gmail.com user
Content-Type: application/json

{
    "number": "7647 7164 5381 8405",
    "validTill": "2028-06-12",
    "code": 216
}

###
PUT /cards/deposit?amount=350.0
Host: localhost:9000
Content-Type: application/json

{
    "number": "7647 7164 5381 8405",
    "validTill": "2028-06-12",
    "code": 216,
    "pin": 2356
}

###
PUT /cards/withdraw?amount=300.0
Host: localhost:9000
Content-Type: application/json

{
    "number": "7647 7164 5381 8405",
    "validTill": "2028-06-12",
    "code": 216,
    "pin": 2356
}

###
PUT /cards/transfer?fromCardId=7826aa63-18cf-4b5b-87f6-ec9b88c8b42b&toCardId=b33a7ebb-b92a-483b-b1bc-cdf6d447d774&amount=150.0
Host: localhost:9000
Authorization: Basic user@gmail.com user

###
PUT /cards/transfer?fromCardId=b33a7ebb-b92a-483b-b1bc-cdf6d447d774&toCardId=7826aa63-18cf-4b5b-87f6-ec9b88c8b42b&amount=150.0
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
PUT /cards/activate-deactivate?cardId=7826aa63-18cf-4b5b-87f6-ec9b88c8b42b&enabled=true
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
GET /operations/by-card?cardId=7826aa63-18cf-4b5b-87f6-ec9b88c8b42b
Host: localhost:9000
Authorization: Basic user@gmail.com user

###
GET /operations/by-identity?identityId=36c26d47-ff67-47c9-a7ba-1a1d0de6f52b
Host: localhost:9000
Authorization: Basic user@gmail.com user

###
GET /transfers/by-sender-card?senderCardId=7826aa63-18cf-4b5b-87f6-ec9b88c8b42b
Host: localhost:9000
Authorization: Basic user@gmail.com user

###
GET /transfers/by-identity?identityId=36c26d47-ff67-47c9-a7ba-1a1d0de6f52b
Host: localhost:9000
Authorization: Basic user@gmail.com user