
###
GET /security/csrf-token
Host: localhost:9000

###
POST /identities/create
Host: localhost:9000
Content-Type: application/json

{
    "authority": "ADMIN",
    "name": "Igor",
    "surname": "Polushev",
    "patronymic": "Petrovich",
    "password": "admin",
    "email": "admin@gmail.com",
    "phone": "+7(913)-905-7556",
    "passport": "4657 687943",
    "enabled": true
}

###
POST /identities/create
Host: localhost:9000
Content-Type: application/json

{
    "authority": "USER",
    "name": "Vadim",
    "surname": "Krivov",
    "patronymic": "Olegovich",
    "password": "user",
    "email": "user@gmail.com",
    "phone": "+7(952)-563-7942",
    "passport": "8696 761238",
    "enabled": true
}

###
PUT /identities/update?identityId=acf2d526-b745-465c-b82f-cb07837f361c
Host: localhost:9000
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "phone": "+7(952)-295-5690"
}

###
GET /identities
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
GET /identities/by-email?email=user@gmail.com
Host: localhost:9000
Authorization: Basic user@gmail.com user

###
GET /identities/by-id?identityId=acf2d526-b745-465c-b82f-cb07837f361c
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
DELETE /identities/delete?identityId=acf2d526-b745-465c-b82f-cb07837f361c
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
PATCH /identities/change-password?identityId=41d8248f-826c-4f78-a818-94bd6c909aaa&password=adminadmin
Host: localhost:9000
Authorization: Basic admin@gmail.com admin

###
PATCH /identities/enable-disable?identityId=36c26d47-ff67-47c9-a7ba-1a1d0de6f52b&enabled=true
Host: localhost:9000
Authorization: Basic admin@gmail.com admin